
import { AppTexts, Property, Language } from './types';

export const DICTIONARY: Record<Language, AppTexts> = {
  es: {
    welcome: "Bienvenido",
    enter_code: "Ingrese su código de reserva",
    continue: "Continuar",
    wifi: "WiFi",
    checkin_checkout: "Check-in / Out",
    rules: "Reglas",
    guide: "Guía del Apartamento",
    area: "Recomendaciones",
    contact: "Contacto",
    error_not_found: "Apartamento o código no encontrado",
    loading: "Cargando experiencia...",
    copy_pw: "Copiar contraseña",
    copied: "¡Copiado!",
    show_pw: "Mostrar",
    hide_pw: "Ocultar",
    register_checkin: "Registrar Check-in",
    register_checkout: "Registrar Check-out",
    guest_name: "Nombre del huésped",
    optional: "Opcional",
    checkin_instructions: "El check-in está disponible a partir de las 3:00 PM. Por favor, asegúrese de haber recibido las llaves o el código de acceso.",
    checkout_instructions: "El check-out debe realizarse antes de las 11:00 AM. Recuerde apagar luces y aire acondicionado.",
    whatsapp_host: "WhatsApp Anfitrión",
    call_host: "Llamar Anfitrión",
    emergency_title: "Emergencias",
    admin_info: "Información Administración",
    language_label: "Idioma",
    success_check: "¡Registro exitoso!",
    server_error: "El servidor no respondió. Verifica el backend.",
    critical_error: "Error crítico al intentar registrar.",
    about_place: "Acerca del lugar",
    rooms: "Hab",
    baths: "Baños",
    guests_cap: "Huesp",
    access_code_title: "Acceso Temporal Por una unica Ves",
    access_code_desc: "Usa este código para abrir la cerradura inteligente durante tu estancia.",
    // Admin
    admin_panel_title: "Panel Propietario",
    admin_login_title: "Acceso Propietario",
    admin_master_key: "Ingrese Clave Maestra (Property ID)",
    admin_authenticate: "Autenticar",
    admin_search_booking: "Buscar por Código",
    admin_return_home: "Regresar al Inicio",
    admin_edit_active: "Modo Edición Activo",
    admin_hint: "Desde aquí puedes actualizar la información que ven tus huéspedes en tiempo real.",
    admin_access_info: "Información de Acceso",
    admin_booking_label: "Código de Reserva (Login)",
    admin_door_label: "Clave de Puerta Check-in",
    admin_property_info: "Datos del Inmueble",
    admin_commercial_name: "Nombre Comercial",
    admin_address_label: "Dirección",
    admin_short_desc_label: "Descripción Breve",
    admin_cover_url_label: "URL Foto Portada",
    admin_host_url_label: "URL Foto Anfitrión",
    admin_wifi_label: "Acceso WiFi",
    admin_ssid_label: "SSID (Red)",
    admin_password_label: "Clave",
    admin_guide_label: "Guía del Apartamento",
    admin_simple_format: "Formato Simple",
    admin_guide_placeholder: "Título: Descripción...",
    admin_rules_label: "Reglas",
    admin_rules_placeholder: "Una regla por línea...",
    admin_area_generator: "Generador de Zona",
    admin_area_hint: "Selecciona qué categorías incluir (Max 5):",
    admin_generate_recs: "Generar Recomendaciones",
    admin_searching: "Buscando sitios...",
    admin_publish_changes: "Publicar Cambios",
    admin_publishing: "Publicando...",
    admin_contact_label: "Contacto",
    admin_host_name_label: "Nombre Anfitrión"
  },
  en: {
    welcome: "Welcome",
    enter_code: "Enter your booking code",
    continue: "Continue",
    wifi: "WiFi",
    checkin_checkout: "Check-in / Out",
    rules: "Rules",
    guide: "Apartment Guide",
    area: "Area Tips",
    contact: "Contact",
    error_not_found: "Property or code not found",
    loading: "Loading experience...",
    copy_pw: "Copy password",
    copied: "Copied!",
    show_pw: "Show",
    hide_pw: "Hide",
    register_checkin: "Register Check-in",
    register_checkout: "Register Check-out",
    guest_name: "Guest Name",
    optional: "Optional",
    checkin_instructions: "Check-in is available from 3:00 PM. Please make sure you have received your keys or access code.",
    checkout_instructions: "Check-out must be done before 11:00 AM. Remember to turn off lights and AC.",
    whatsapp_host: "WhatsApp Host",
    call_host: "Call Host",
    emergency_title: "Emergencies",
    admin_info: "Building Info",
    language_label: "Language",
    success_check: "Registration successful!",
    server_error: "Server did not respond. Check backend.",
    critical_error: "Critical error during registration.",
    about_place: "About the place",
    rooms: "Rooms",
    baths: "Baths",
    guests_cap: "Guests",
    access_code_title: "Temporary Access - One time only",
    access_code_desc: "Use this code to open the smart lock during your stay.",
    // Admin
    admin_panel_title: "Owner Panel",
    admin_login_title: "Owner Access",
    admin_master_key: "Enter Master Key (Property ID)",
    admin_authenticate: "Authenticate",
    admin_search_booking: "Search by Code",
    admin_return_home: "Return Home",
    admin_edit_active: "Edit Mode Active",
    admin_hint: "From here you can update the information your guests see in real time.",
    admin_access_info: "Access Information",
    admin_booking_label: "Booking Code (Login)",
    admin_door_label: "Check-in Door Code",
    admin_property_info: "Property Data",
    admin_commercial_name: "Commercial Name",
    admin_address_label: "Address",
    admin_short_desc_label: "Short Description",
    admin_cover_url_label: "Cover Photo URL",
    admin_host_url_label: "Host Photo URL",
    admin_wifi_label: "WiFi Access",
    admin_ssid_label: "SSID (Network)",
    admin_password_label: "Password",
    admin_guide_label: "Apartment Guide",
    admin_simple_format: "Simple Format",
    admin_guide_placeholder: "Title: Description...",
    admin_rules_label: "Rules",
    admin_rules_placeholder: "One rule per line...",
    admin_area_generator: "Area Generator",
    admin_area_hint: "Select categories to include (Max 5):",
    admin_generate_recs: "Generate Recommendations",
    admin_searching: "Searching places...",
    admin_publish_changes: "Publish Changes",
    admin_publishing: "Publishing...",
    admin_contact_label: "Contact",
    admin_host_name_label: "Host Name"
  }
};

// Se mantiene el mock para pruebas locales
export const MOCK_PROPERTIES: Property[] = [
  {
    property_id: "APT001",
    codigo_reserva: "RESERVA123",
    nombre_apartamento: "Apartamento Vista Mar Pozos Colorados",
    ciudad: "Santa Marta",
    direccion: "Carrera 1 # 10-20, Edificio Ocean",
    foto_portada_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800",
    wifi_ssid: "Ocean_Guest_001",
    wifi_password: "playa_brisa_mar",
    num_habitaciones: 2,
    num_banos: 2,
    capacidad_personas: 6,
    descripcion_corta: "Hermoso apartamento con vista directo al mar en la mejor zona de Pozos Colorados. Totalmente equipado.",
    reglas: "Prohibido fumar en el interior.\nNo se permiten mascotas.\nRespetar el horario de silencio (10 PM - 8 AM).\nNo se permiten fiestas.",
    guia_uso_json: JSON.stringify({
      "Aire Acondicionado": "No bajar de 22°C para evitar congelamiento. Mantener ventanas cerradas.",
      "Televisor": "Use el control LG negro. El acceso a Netflix es libre, no cambie de cuenta.",
      "Cocina": "La estufa es de inducción. Solo use ollas con base ferrosa.",
      "Calentador": "Ubicado en el área de labores. Ya está configurado, no tocar perillas."
    }),
    recomendaciones_zona_json: JSON.stringify([
      {
        nombre: "Playa Pozos Colorados",
        tipo: "Playa",
        descripcion: "Acceso directo desde el edificio. Arena blanca y aguas tranquilas.",
        url_mapa: "https://maps.google.com/?q=Pozos+Colorados"
      }
    ]),
    whatsapp_number: "+57 300 123 4567",
    phone_number: "+57 300 123 4567",
    host_name: "Andrés Rodríguez",
    host_photo_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
  }
];
